### ISSUE TITLE
Logs are missing some output in parenthases

### ISSUE THREAD

**Issue by applejag** [kubecolor/kubecolor#167]
### Expected behavior

Colorizes the following:

```console
$ echo '(foo bar)' | kubecolor logs --kubecolor-stdin
(foo bar)
```

### Current behavior

Missing text within parenthases

```console
$ echo '(foo bar)' | kubecolor logs --kubecolor-stdin
(foo)
```

### Package manager

Compiled from source using `go install`

### What operating system are you running?

Linux

### Kubectl and kubecolor version

```yaml
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Kubecolor Version: v0.3.4-0.20240822021250-789107ee3e21
```
