### ISSUE TITLE
Colorize depends on flag position

### ISSUE THREAD

**Issue by chrede88** [kubecolor/kubecolor#187]
### Expected behavior

Colorize when listing pods in namespace called `rook-ceph` doesn't work if I specify the namespace flag first.

### Current behavior

`k -n rook-ceph get po` doesn't work, while `k get po -n rook-ceph` does work. I've tested on all my namespaces, it only happens for `rook-ceph`.

It's not the dash as other namespaces with a "dashed" name works fine.
<img width="1578" alt="Screenshot 2024-10-04 at 6 47 29 PM" src="https://github.com/user-attachments/assets/42e1a684-b4e9-4287-b611-9037de88b9aa">

### Package manager

Homebrew

### What operating system are you running?

Mac

### Kubectl and kubecolor version

```yaml
Client Version: v1.31.1
Kustomize Version: v5.4.2
Kubecolor Version: v0.4.0
```
