### ISSUE TITLE
Diff show different colors based on action

### ISSUE THREAD

**Issue by tzabbi** [kubecolor/kubecolor#190]
### Description

I tried kubecolor for show me the diff of deployment in hope it shows lines with`-` red and with `+` with green color. But instead, every line is green. I would like to see the differences in another color.

EDIT:
current output:

![image](https://github.com/user-attachments/assets/f5c92c85-bea2-4fe4-8edd-cfd4c1909962)

desired output (output from helm)
![image](https://github.com/user-attachments/assets/d51376d5-b763-4ac1-9f72-6d5d1ce5e276)

### Kubectl and kubecolor version

```yaml
❯ kubecolor version --client
Client Version: v1.31.2
Kustomize Version: v5.4.2
Kubecolor Version: v0.4.0
```
