### ISSUE TITLE
kubecolor completion has color

### ISSUE THREAD

**Issue by mike2194** [kubecolor/kubecolor#195]
### Expected behavior

prompt completion should not be colorized:
```
 ~ % kc annotate
Completing completions
annotate       -- Update the annotations on a resource
api-resources  -- Print the supported API resources on the server
api-versions   -- Print the supported API versions on the server, in the form of "group/version"
apply          -- Apply a configuration to a resource by file name or stdin
```

### Current behavior

when completing a command, the completion includes raw color strings:
```
 ~ % kc $'\033'\[33mannotate
```

### Package manager

Other (please specify in "Additional context" section)

### Kubectl and kubecolor version

```yaml
~ % /usr/bin/kubecolor version --client
Client Version: v1.29.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```
```
Package: kubecolor
Version: 0.0.20-2ubuntu0.24.04.2
Built-Using: golang-1.22 (= 1.22.2-2ubuntu0.3), golang-github-google-go-cmp (= 0.6.0-1), golang-github-makenowjust-heredoc (= 1.0.0-1), golang-github-mattn-go-colorable (= 0.1.13-1), golang-github-mattn-go-isatty (= 0.0.20-1), golang-golang-x-sys (= 0.17.0-1)
```
```


### Additional context

installed with `apt install kubecolor`
