### ISSUE TITLE
Kubectl config does not provide color

### ISSUE THREAD

**Issue by tzabbi** [kubecolor/kubecolor#202]
### Description

Kubecolor does not work for kubectl config when I want to see my current context or set it.

### Kubectl and kubecolor version

```yaml
❯ kubecolor version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.1
Kubecolor Version: v0.4.0
```
