### ISSUE TITLE
Multiline YAML breaks colorization and removes quotation marks

### ISSUE THREAD

**Issue by larsgerber** [kubecolor/kubecolor#203]
### Expected behavior

The multiline content is skipped like in the GitHub codeblock.

### Current behavior

The following manifest breaks the colorization:
```yaml
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  annotations:
    venafi.cert-manager.io/custom-fields: |-
      [
        {"name": "field-name", "value": "field value"},
        {"name": "field-name-2", "value": "field value 2"}
      ]
  name: test
  namespace: default
```

![Screenshot 2024-12-07 at 21 46 32](https://github.com/user-attachments/assets/2d487a3c-f60d-4827-a219-3e87d66f5cab)

The example content is from here: https://cert-manager.io/docs/configuration/venafi/#custom-fields

### Package manager

Homebrew

### What operating system are you running?

Mac

### Kubectl and kubecolor version

```yaml
Client Version: v1.31.3
Kustomize Version: v5.4.2
Kubecolor Version: v0.4.0
```

### Additional context

There is no output manipulation when `--plain` is used or when the output is piped.

```bash
k create -f input.yaml --dry-run=client -o yaml | tee output.yaml
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  annotations:
    venafi.cert-manager.io/custom-fields: |-
      [
        {"name": "field-name", "value": "field value"},
        {"name": "field-name-2", "value": "field value 2"}
      ]
  name: test
  namespace: default
```

```bash
difft input.yaml output.yaml
output.yaml --- YAML
No changes.
```
