### ISSUE TITLE
Kubecolor does not show color when running under `watch`

### ISSUE THREAD

**Issue by surajssd** [kubecolor/kubecolor#221]
### Description

Whenever I am waiting for certain pods to show up, I run a `watch kubectl get pods` but kubecolor does not show colors there.

<img width="1424" alt="Image" src="https://github.com/user-attachments/assets/9630d26b-d11b-44f8-841c-8b569e530cdf" />

### Kubectl and kubecolor version

```yaml
✗ kubecolor version --client
Client Version: v1.32.3
Kustomize Version: v5.5.0
Kubecolor Version: v0.5.0
```
