### ISSUE TITLE
Support for kuberc

### ISSUE THREAD

**Issue by Blarc** [kubecolor/kubecolor#248]
### Description

Hey,

thanks for this awesome project 🙏 . Now that I use it, I can't image to work without it.

I'm not sure if you saw, but kubectl got a new feature called **kuberc** that allows you to add your own aliases: https://cloudfleet.ai/blog/cloud-native-how-to/2025-05-customizing-kubectl-with-kuberc/.

I was wondering if it's possible to support it with kubecolor?

Thanks.

### Kubectl and kubecolor version

```yaml
Client Version: v1.33.1
Kustomize Version: v5.6.0
Kubecolor Version: 0.5.1
```
